name: tentura
description: 'Social network for communities'
publish_to: 'none'

version: 1.2.12

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ^3.32.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tentura_root:
    path: ../../

  # Common
  uuid: ^4.4.2
  get_it: ^8.2.0
  latlong2: ^0.9.1
  injectable: ^2.5.1
  auto_route: ^9.0.0
  collection: ^1.19.1
  built_value: ^8.9.5
  http_parser: ^4.1.2
  flutter_bloc: ^9.1.1
  synchronized: ^3.4.0
  json_annotation: ^4.9.0
  built_collection: ^5.1.1
  freezed_annotation: ^2.4.4

  # Platform related
  web: ^1.1.1
  http: ^1.5.0
  meta: ^1.16.0
  drift: ^2.26.1
  mailto: ^2.0.0
  geocoding: ^4.0.0
  drift_dev: ^2.26.0
  geolocator: ^14.0.2
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  drift_flutter: ^0.2.5
  firebase_core: ^4.0.0
  share_handler: ^0.0.25
  mobile_scanner: ^7.0.1
  firebase_messaging: ^16.0.0
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^10.0.0-beta.4

  # Logs & Stats
  logger: ^2.6.1
  sentry_drift: ^9.6.0
  sentry_flutter: ^9.6.0

  # Remote API related
  ferry: ^0.16.0
  gql_exec: ^1.0.0
  gql_http_link: ^1.1.0
  gql_error_link: ^1.0.0
  gql_dedupe_link: ^2.0.3
  ed25519_edwards: ^0.3.1
  dart_jsonwebtoken: ^3.2.0
  web_socket_client: ^0.2.1
  gql_websocket_link: ^2.0.1

  # UI related
  nil: ^1.1.1
  intl: ^0.20.2
  image: ^4.5.4
  readmore: ^3.0.0
  qr_flutter: ^4.1.0
  flutter_map: ^8.2.1
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0
  validatorless: ^1.2.4
  blurhash_shader: ^1.1.2
  vector_graphics: ^1.1.19
  intl_translation: ^0.20.1
  visibility_detector: ^0.4.0
  force_directed_graphview: ^0.6.2
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  freezed: ^2.5.7
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  ferry_generator: ^0.12.0
  json_serializable: ^6.9.0
  sentry_dart_plugin: ^3.0.0
  very_good_analysis: ^9.0.0
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Tentura
      fonts:
        - asset: fonts/tentura-icons.ttf
  assets:
    - images/placeholder/
    - images/intro.svg.vec

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  ignore_missing: true
  project: tentura
