name: tentura
description: 'Social network for communities'
publish_to: 'none'

version: 0.10.3

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ^3.27.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  uuid:
  drift:
  get_it:
  logger:
  drift_dev:
  collection:
  injectable:

  intl: ^0.20.1
  latlong2: ^0.9.1
  auto_route: ^9.2.2
  built_value: ^8.9.3
  flutter_bloc: ^8.1.6
  synchronized: ^3.3.0
  sentry_flutter: ^8.12.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Platform related
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  share_plus: ^10.1.3
  image_picker: ^1.1.2
  drift_flutter: ^0.2.4
  share_handler: ^0.0.22
  mobile_scanner: ^7.0.0-beta.3
  flutter_secure_storage: ^9.2.3

  # UI related
  nil: ^1.1.1
  readmore: ^3.0.0
  qr_flutter: ^4.1.0
  flutter_map: ^7.0.2
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  mesh_gradient: ^1.3.8
  vector_graphics: ^1.1.15
  visibility_detector: ^0.4.0
  flutter_native_splash: ^2.4.3
  # smooth_page_indicator: ^1.2.0
  force_directed_graphview: ^0.6.2
  scrollable_positioned_list: ^0.3.8
  flutter_map_cancellable_tile_provider: ^3.0.0

  # Local
  tentura_sdk:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable:
  very_good_analysis:
  injectable_generator:

  freezed: ^2.5.7
  ferry_generator: ^0.12.0
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  fonts:
    - family: Tentura
      fonts:
        - asset: assets/fonts/tentura-icons.ttf
  assets:
    - assets/images/
    - assets/intro/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  ignore_missing: true
