name: tentura
description: 'Social network for communities'
publish_to: 'none'

version: 0.13.8

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: ^3.29.2

resolution: workspace

dependencies:
  # From workspace
  flutter:
    sdk: flutter
  http:
  intl:
  uuid:
  image:
  get_it:
  latlong2:
  collection:
  injectable:
  tentura_root:
  google_fonts:
  blurhash_dart:
  ed25519_edwards:
  dart_jsonwebtoken:
  freezed_annotation:

  # Common
  logger: ^2.5.0
  auto_route: ^9.3.0
  built_value: ^8.9.5
  flutter_bloc: ^9.1.0
  synchronized: ^3.3.0
  sentry_drift: ^8.14.0
  sentry_flutter: ^8.14.0
  json_annotation: ^4.9.0
  intl_translation: ^0.20.1

  # Platform
  drift: ^2.26.0
  ferry: ^0.16.0
  mailto: ^2.0.0
  gql_exec: ^1.0.0
  geocoding: ^3.0.0
  drift_dev: ^2.26.0
  geolocator: ^13.0.3
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  drift_flutter: ^0.2.4
  gql_http_link: ^1.1.0
  share_handler: ^0.0.22
  gql_error_link: ^1.0.0
  gql_dedupe_link: ^2.0.3
  gql_websocket_link: ^2.0.1
  mobile_scanner: ^7.0.0-beta.8
  flutter_secure_storage: ^10.0.0-beta.4

  # UI related
  nil: ^1.1.1
  readmore: ^3.0.0
  qr_flutter: ^4.1.0
  flutter_map: ^8.1.1
  flutter_svg: ^2.0.17
  validatorless: ^1.2.4
  blurhash_shader: ^1.1.2
  vector_graphics: ^1.1.18
  visibility_detector: ^0.4.0
  flutter_native_splash: ^2.4.5
  force_directed_graphview: ^0.6.2
  scrollable_positioned_list: ^0.3.8
  flutter_map_cancellable_tile_provider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner:
  json_serializable:
  very_good_analysis:
  injectable_generator:

  ferry_generator: ^0.12.0
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  fonts:
    - family: Tentura
      fonts:
        - asset: fonts/tentura-icons.ttf
  assets:
    - images/placeholder/
    - images/intro.svg.vec

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  ignore_missing: true
