name: tentura_root
publish_to: none

environment:
  sdk: '>=3.7.2 <4.0.0'

workspace:
  - packages/client
  - packages/server
  - packages/widgetbook

dependencies:
  uuid: ^4.4.2
  http: ^1.2.2
  intl: ^0.19.0
  meta: ^1.16.0
  faker: ^2.2.0
  image: ^4.5.4
  get_it: ^8.0.3
  latlong2: ^0.9.1
  faker_dart: ^0.2.2
  injectable: ^2.5.0
  collection: ^1.19.1
  google_fonts: ^6.2.1
  blurhash_dart: ^1.2.1
  ed25519_edwards: ^0.3.1
  dart_jsonwebtoken: ^3.2.0
  freezed_annotation: ^2.4.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  lints: ^5.1.1
  freezed: ^2.5.7
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  very_good_analysis: ^7.0.0
  injectable_generator: ^2.6.2

flutter:
  generate: true
