name: tentura_root
publish_to: none

version: 0.0.2

environment:
  sdk: '>=3.6.1 <4.0.0'

workspace:
  - packages/client
  - packages/server
  - packages/tentura_sdk
  - packages/widgetbook

dependencies:
  uuid: ^4.4.2
  intl: ^0.19.0
  meta: ^1.15.0
  faker: ^2.2.0
  get_it: ^8.0.3
  latlong2: ^0.9.1
  faker_dart: ^0.2.2
  injectable: ^2.5.0
  collection: ^1.19.0
  google_fonts: ^6.2.1
  blurhash_dart: ^1.2.1
  ed25519_edwards: ^0.3.1
  dart_jsonwebtoken: ^2.16.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  freezed: ^2.5.7
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  very_good_analysis: ^7.0.0
  injectable_generator: ^2.6.2
