name: tentura_root
publish_to: none

version: 0.0.1

environment:
  sdk: ^3.6.0

workspace:
  - packages/client
  - packages/tentura_sdk
  - packages/widgetbook

dev_dependencies:
  build_runner: ^2.4.14
  very_good_analysis: ^6.0.0
