name: tentura_root
publish_to: none

version: 0.0.1

environment:
  sdk: ^3.6.0

workspace:
  - packages/client
  - packages/server
  - packages/tentura_sdk
  - packages/widgetbook

dependencies:
  uuid: ^4.4.2
  faker: ^2.2.0
  drift: ^2.23.0
  get_it: ^8.0.3
  logger: ^2.5.0
  sentry: ^8.12.0
  mockito: ^5.4.5
  drift_dev: ^2.23.0
  injectable: ^2.5.0
  collection: ^1.19.0
  ed25519_edwards: ^0.3.1

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  very_good_analysis: ^7.0.0
  injectable_generator: ^2.6.2
