name: tentura_server
description: Tentura server API
publish_to: none

version: 0.1.5

environment:
  sdk: '>=3.7.2 <4.0.0'

resolution: workspace

dependencies:
  meta:
  uuid:
  faker:
  image:
  get_it:
  latlong2:
  collection:
  injectable:
  tentura_root:
  blurhash_dart:
  dart_jsonwebtoken:
  freezed_annotation:

  args: ^2.7.0
  minio: ^3.5.7
  jaspr: ^0.17.0
  postgres: ^3.5.4
  shelf_plus: ^1.10.0
  stormberry: ^0.15.0
  angel3_graphql: ^8.3.0
  graphql_schema2: ^6.3.0
  graphql_server2: ^6.3.0
  shelf_multipart: ^2.0.1
  shelf_cors_headers: ^0.1.5
  # neat_periodic_task: ^2.0.1

dev_dependencies:
  lints:
  freezed:
  build_runner:
  json_serializable:
  very_good_analysis:
  injectable_generator:

  test: ^1.25.15
  jaspr_builder: ^0.17.0
  build_web_compilers: ^4.1.3

jaspr:
  mode: server
