name: tentura_server
description: Tentura server API
publish_to: none

version: 0.5.12

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  tentura_root:
    path: ../../

  http: ^1.5.0
  uuid: ^4.4.2
  meta: ^1.17.0
  faker: ^2.2.0
  image: ^4.5.4
  minio: ^3.5.7
  drift: ^2.28.1
  jaspr: ^0.20.0
  crypto: ^3.0.6
  get_it: ^8.2.0
  logging: ^1.3.0
  migrant: ^0.3.0
  latlong2: ^0.9.1
  postgres: ^3.5.6
  injectable: ^2.5.1
  collection: ^1.19.1
  shelf_plus: ^1.10.1
  pg_job_queue: ^0.0.2
  blurhash_dart: ^1.2.1
  angel3_graphql: ^8.3.0
  drift_postgres: ^1.3.1
  graphql_schema2: ^6.3.0
  graphql_server2: ^6.3.0
  json_annotation: ^4.9.0
  shelf_multipart: ^2.0.1
  dart_jsonwebtoken: ^3.2.0
  freezed_annotation: ^3.1.0
  shelf_cors_headers: ^0.1.5
  migrant_db_postgresql: ^0.3.0

dev_dependencies:
  test: ^1.26.3
  freezed: ^3.1.0
  drift_dev: ^2.28.0
  build_runner: ^2.5.4
  jaspr_builder: ^0.20.0
  json_serializable: ^6.9.5
  very_good_analysis: ^9.0.0
  injectable_generator: ^2.7.0

jaspr:
  mode: server
