name: tentura_server
description: Tentura server API
publish_to: none

version: 0.0.7

environment:
  sdk: '>=3.6.2 <4.0.0'

resolution: workspace

dependencies:
  meta:
  uuid:
  faker:
  image:
  get_it:
  latlong2:
  injectable:
  tentura_root:
  blurhash_dart:
  dart_jsonwebtoken:
  freezed_annotation:

  jaspr: ^0.17.0
  postgres: ^3.4.8
  shelf_plus: ^1.10.0
  stormberry: ^0.15.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  freezed:
  build_runner:
  json_serializable:
  very_good_analysis:
  injectable_generator:

  test: ^1.25.8
  jaspr_builder: ^0.17.0
  build_web_compilers: ^4.1.1

jaspr:
  mode: server
