name: tentura_widgetbook
description: Widgetbook for Tentura
publish_to: none

version: 0.1.0

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ^3.38.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tentura:
    path: ../client

  get_it: ^9.1.0
  logger: ^2.6.2
  injectable: ^2.6.0
  widgetbook: ^3.20.1
  google_fonts: ^6.3.1
  blurhash_shader: ^1.1.2
  widgetbook_annotation: ^3.9.0
  gql_code_builder_serializers: ^0.1.0

dev_dependencies:
  build_runner: ^2.10.4
  very_good_analysis: ^10.0.0
  injectable_generator: ^2.9.1
  widgetbook_generator: ^3.20.0

flutter:
  uses-material-design: true
