name: tentura_widgetbook
description: Widgetbook for Tentura
publish_to: none

version: 0.0.6

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ^3.35.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tentura:
    path: ../client

  get_it: ^8.2.0
  logger: ^2.6.1
  injectable: ^2.5.1
  widgetbook: ^3.16.0
  google_fonts: ^6.3.1
  blurhash_shader: ^1.1.2
  widgetbook_annotation: ^3.7.0
  gql_code_builder_serializers: ^0.1.0

dev_dependencies:
  build_runner: ^2.7.0
  very_good_analysis: ^9.0.0
  injectable_generator: ^2.8.1
  widgetbook_generator: ^3.16.0

flutter:
  uses-material-design: true
