name: tentura_widgetbook
description: Widgetbook for Tentura
publish_to: none

version: 0.0.2

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ^3.29.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  get_it:
  logger:
  tentura:
  injectable:
  google_fonts:

  widgetbook: ^3.10.1
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  build_runner:
  very_good_analysis:
  injectable_generator:

  widgetbook_generator: ^3.9.0

flutter:
  uses-material-design: true
