name: tentura_sdk
description: Dart package for using Tentura server API
publish_to: none

version: 0.0.3

environment:
  sdk: '>=3.6.1 <4.0.0'

resolution: workspace

dependencies:
  logger:
  tentura_root:
  ed25519_edwards:
  dart_jsonwebtoken:

  http: ^1.2.2
  ferry: ^0.16.0
  gql_exec: ^1.0.0
  gql_http_link: ^1.1.0
  gql_error_link: ^1.0.0
  gql_dedupe_link: ^2.0.3
  gql_websocket_link: ^2.0.1

dev_dependencies:
  very_good_analysis:
